# Generated by Django 5.1.2 on 2024-11-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='subcategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
