# Generated by Django 5.1.2 on 2024-11-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_information_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
