# Generated by Django 5.1.2 on 2024-11-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="information",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="information",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
