# Generated by Django 5.1.2 on 2024-11-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0005_remove_information_subcategory_information_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
