# Generated by Django 5.1.2 on 2024-11-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0006_alter_information_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="summary",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
