# Generated by Django 5.1.2 on 2024-11-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_information_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='summary',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
